spring:
 profiles:
  active:
  -dec
---
spring:
 profiles: dev
 application:
   name: microservicecloud01-config-atguigu-dev 
---
spring:
 profiles: test
 application:
   name: microservicecloud01-config-atguigu-test